# When updating resover, also update .travis.yml
resolver: lts-11.8

extra-deps:
  - aeson-1.3.1.0
  - async-2.2.1
  - foldl-1.4.0
  - list-transformer-1.0.4
  - megaparsec-6.5.0
  - monad-ste-0.1.0.0
  - network-2.7.0.0
  - nf-1.0.1.0
  - reactive-banana-1.2.0.0
  - unagi-chan-0.4.1.0

flags:
  contravariant:
    statevar: false

  mitchell-stdlib:
    aeson: true
    ansi-terminal: true
    async: true
    atomic-primops: true
    base16-bytestring: true
    bits: true
    bytestring-trie: true
    comonad: true
    compact: true
    constraints: true
    contravariant: true
    contravariant-extras: true
    deepseq: true
    directory: true
    distributive: true
    dlist: true
    erf: true
    extra: true
    filepath: true
    foldl: true
    gauge: true
    hashable: true
    hedgehog: true
    heaps: true
    lens: true
    list-transformer: true
    logict: true
    managed: true
    megaparsec: true
    mmorph: true
    monad-ste: true
    mtl: true
    multiset: true
    mwc-random: true
    network: true
    nf: true
    optparse-applicative: true
    parallel: true
    prettyprinter: true
    primitive: true
    profunctors: true
    psqueues: true
    reactive-banana: true
    reflection: true
    regex-applicative: true
    safe-exceptions: true
    scientific: true
    semigroups: true
    stm: true
    stm-containers: true
    tagged: true
    text-short: true
    time: true
    transformers: true
    transformers-base: true
    typed-process: true
    unagi-chan: true
    unix: true
    unliftio: true
    unordered-containers: true
    vector: true
    weigh: true
    writer-cps-mtl: true

allow-newer: true
