resolver: lts-11.8

extra-deps:
  - aeson-1.3.1.0
  - async-2.2.1
  - foldl-1.4.0
  - list-transformer-1.0.4
  - megaparsec-6.5.0
  - monad-ste-0.1.0.0
  - network-2.7.0.0
  - nf-1.0.1.0
  - reactive-banana-1.2.0.0
  - unagi-chan-0.4.1.0

flags:
  contravariant:
    statevar: false

  mitchell-stdlib:
    dep-aeson: true
    dep-ansi-terminal: true
    dep-async: true
    dep-atomic-primops: true
    dep-base16-bytestring: true
    dep-bits: true
    dep-bytestring-trie: true
    dep-comonad: true
    dep-compact: true
    dep-constraints: true
    dep-contravariant: true
    dep-contravariant-extras: true
    dep-deepseq: true
    dep-directory: true
    dep-distributive: true
    dep-dlist: true
    dep-erf: true
    dep-extra: true
    dep-filepath: true
    dep-foldl: true
    dep-gauge: true
    dep-hashable: true
    dep-hedgehog: true
    dep-heaps: true
    dep-lens: true
    dep-list-transformer: true
    dep-logict: true
    dep-managed: true
    dep-megaparsec: true
    dep-mmorph: true
    dep-monad-ste: true
    dep-mtl: true
    dep-multiset: true
    dep-mwc-random: true
    dep-network: true
    dep-nf: true
    dep-optparse-applicative: true
    dep-parallel: true
    dep-prettyprinter: true
    dep-primitive: true
    dep-profunctors: true
    dep-psqueues: true
    dep-reactive-banana: true
    dep-reflection: true
    dep-regex-applicative: true
    dep-safe-exceptions: true
    dep-scientific: true
    dep-semigroups: true
    dep-stm: true
    dep-stm-containers: true
    dep-tagged: true
    dep-text-short: true
    dep-time: true
    dep-transformers: true
    dep-transformers-base: true
    dep-typed-process: true
    dep-unagi-chan: true
    dep-unix: true
    dep-unliftio: true
    dep-unordered-containers: true
    dep-vector: true
    dep-weigh: true
    dep-writer-cps-mtl: true

allow-newer: true
