sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work/install

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal setup
  - stack --no-terminal build --fast --only-dependencies

script:
  - stack --no-terminal build --fast --bench --no-run-benchmarks
  - curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
