resolver: lts-11.8

extra-deps:
  - aeson-1.3.1.0
  - async-2.2.1
  - base-orphans-0.8
  - cborg-0.2.0.0
  - containers-0.5.11.0
  - directory-1.3.3.1
  - exceptions-0.10.0
  - extra-1.6.11
  - filepath-1.4.2.1
  - foldl-1.4.4
  - free-5.1
  - half-0.3
  - insert-ordered-containers-0.2.1.0
  - lifted-async-0.10.0.2
  - list-transformer-1.0.4
  - megaparsec-6.5.0
  - monad-ste-0.1.0.0
  - multiset-0.3.4
  - network-2.7.0.0
  - nf-1.0.1.0
  - parser-combinators-1.0.0
  - pcg-random-0.1.3.5
  - primitive-0.6.4.0
  - profunctors-5.3
  - random-bytestring-0.1.3.1
  - reactive-banana-1.2.0.0
  - semigroupoids-5.3.1
  - semilattices-0.0.0.0
  - serialise-0.2.0.0
  - transformers-0.5.5.0
  - transformers-base-0.4.5.2
  - transformers-compat-0.6.2
  - unagi-chan-0.4.1.0
  - vector-builder-0.3.6
  - weigh-0.0.12

flags:
  transformers-compat:
    five-three: true
